steps:
  #Will pull the production image so that our build will be faster
  #as docker uses the cached layers of the old images to build new images.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
      '-c',
      'docker pull gcr.io/$PROJECT_ID/helloworld-nodejs:latest || exit 0'
    ]

  # This step builds the container image and replacing the latest.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/helloworld-nodejs:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/helloworld-nodejs:latest'
      - '.'

  # Apply all the configuration yamls that exist in the k8s/ folder of our application.
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
