apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __REPO_NAME
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # Should be zero unavailable pods while deploying.
      maxSurge: 1 # Should be one new pod at a time.
  replicas: 2
  selector:
    matchLabels:
      app: __REPO_NAME
  template:
    metadata:
      labels:
        app: __REPO_NAME
    spec:
      containers:
        - name: __REPO_NAME
          image: gcr.io/ad4screen-us/__REPO_NAME:__IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
---
apiVersion: v1
kind: Service
metadata:
  name: __REPO_NAME-service
  labels:
    app: __REPO_NAME
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: __REPO_NAME
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: __REPO_NAME-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: hello.testbia.tk
      http:
        paths:
          - backend:
              serviceName: __REPO_NAME-service
              servicePort: 80
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: __REPO_NAME-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: __REPO_NAME
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
