apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-nodejs
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # Should be zero unavailable pods while deploying.
      maxSurge: 1 # Should be one new pod at a time.
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-nodejs
  template:
    metadata:
      labels:
        app: helloworld-nodejs
    spec:
      containers:
        - name: helloworld-nodejs
          image: gcr.io/ad4screen-us/helloworld-nodejs:dazdza
          ports:
            - containerPort: 8080
              name: http
          readinessProbe: # Send an http get request to the path / every five seconds and if it is successful, mark the pod ready and start sending traffic to it.
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-nodejs-service
spec:
  selector:
    app: helloworld-nodejs
  ports:
    - targetPort: 8080
      port: 80
      name: http
  type: LoadBalancer
  loadBalancerIP: 35.247.85.46

